package io.github.alexanderwilhelmsenberg.oneuiorganizer.rules.games

import io.github.alexanderwilhelmsenberg.oneuiorganizer.model.AppCategory
import io.github.alexanderwilhelmsenberg.oneuiorganizer.model.AppId
import io.github.alexanderwilhelmsenberg.oneuiorganizer.rules.KnownAppRule
import io.github.alexanderwilhelmsenberg.oneuiorganizer.rules.KnownAppSelector

object GameKnownAppRules {
    val entries: List<KnownAppRule> =
        listOf(
            // Action & Adventure
            packageRule("com.bandainamcoent.ultimateninjastorm", AppCategory.GAME_ACTION_ADVENTURE),
            packageRule("com.devolverdigital.carrion", AppCategory.GAME_ACTION_ADVENTURE),
            packageRule("com.direlight.grimvalor", AppCategory.GAME_ACTION_ADVENTURE),
            packageRule("com.dishii.mm", AppCategory.GAME_ACTION_ADVENTURE),
            packageRule("com.dishii.soh", AppCategory.GAME_ACTION_ADVENTURE),
            packageRule("com.hg.bfbb", AppCategory.GAME_ACTION_ADVENTURE),
            packageRule("com.navegante.greak", AppCategory.GAME_ACTION_ADVENTURE),
            packageRule("com.netflix.NGP.TMNTShreddersRevenge", AppCategory.GAME_ACTION_ADVENTURE),
            packageRule("com.noodlecake.towagaamongshadows", AppCategory.GAME_ACTION_ADVENTURE),
            packageRule("com.playdigious.sparklite", AppCategory.GAME_ACTION_ADVENTURE),
            packageRule("com.rockstargames.bully", AppCategory.GAME_ACTION_ADVENTURE),
            packageRule("jp.co.capcom.rxdoff", AppCategory.GAME_ACTION_ADVENTURE),
            // RPG
            packageRule("com.aspyr.swkotor", AppCategory.GAME_RPG),
            packageRule("com.aspyr.swkotorii", AppCategory.GAME_RPG),
            packageRule("com.bandainamcoent.dgup_ww", AppCategory.GAME_RPG),
            packageRule("com.beamdog.baldursgateenhancededition", AppCategory.GAME_RPG),
            packageRule("com.bscotch.crashlands", AppCategory.GAME_RPG),
            packageRule("com.bscotch.crashlands2", AppCategory.GAME_RPG),
            packageRule("com.dotemu.titanquest", AppCategory.GAME_RPG),
            packageRule("com.funfizz.palmon.gp", AppCategory.GAME_RPG),
            packageRule("com.haoplay.game.and.hero", AppCategory.GAME_RPG),
            packageRule("com.ilmfinity.evocreo_2", AppCategory.GAME_RPG),
            packageRule("com.jockeholm.undertale", AppCategory.GAME_RPG),
            packageRule("com.kice.afterplace", AppCategory.GAME_RPG),
            packageRule("com.LonelyTroops.HerooftheKingdom", AppCategory.GAME_RPG),
            packageRule("com.murchikstudio.octane100", AppCategory.GAME_RPG),
            packageRule("com.mxdzzus.google", AppCategory.GAME_RPG),
            packageRule("com.netflix.NGP.Moonlighter", AppCategory.GAME_RPG),
            packageRule("com.NextEntry.WS", AppCategory.GAME_RPG),
            packageRule("com.nianticlabs.pokemongo", AppCategory.GAME_RPG),
            packageRule("com.noodlecake.drtc", AppCategory.GAME_RPG),
            packageRule("com.northicagames.kopp3", AppCategory.GAME_RPG),
            packageRule("com.notacult.walkscape", AppCategory.GAME_RPG),
            packageRule("com.playdigious.potionpermit", AppCategory.GAME_RPG),
            packageRule("com.pockettrend.neomonsters", AppCategory.GAME_RPG),
            packageRule("com.RawFury.CassetteBeasts", AppCategory.GAME_RPG),
            packageRule("com.realmsofpixel.ng", AppCategory.GAME_RPG),
            packageRule("com.rtsoft.rtdink", AppCategory.GAME_RPG),
            packageRule("com.StoneGolemStudios.ChronoMonMobile", AppCategory.GAME_RPG),
            packageRule("com.tragsoft.coromon", AppCategory.GAME_RPG),
            packageRule("com.turner.pocketmorties", AppCategory.GAME_RPG),
            packageRule("com.xd.ssrpgen", AppCategory.GAME_RPG),
            packageRule("com.zigzagame.evertale", AppCategory.GAME_RPG),
            packageRule("com.zitga.guardian.war.premium.action.rpg.adventure.games", AppCategory.GAME_RPG),
            packageRule("games.grounded.idleiktah", AppCategory.GAME_RPG),
            packageRule("hb.doom_and_destiny_advanced", AppCategory.GAME_RPG),
            packageRule("ilmfinity.evocreo.main.android", AppCategory.GAME_RPG),
            packageRule("jp.co.capcom.mhsspen", AppCategory.GAME_RPG),
            packageRule("jp.furyu.trinitytrigger", AppCategory.GAME_RPG),
            // Strategy & Simulation
            packageRule("com.bethsoft.stronghold", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.builderment.builderment", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.chucklefish.stardewvalley", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.doghowlgames.thronefall", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.ExabyteGames.FinalOutpost", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.games.foundation", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.gof.global", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.herocraft.game.majesty", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.herocraft.kodp", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.jdogcorp.unnamedspaceidle", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.ndemiccreations.afterinc", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.ninjakiwi.bloonstd6", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.ninjakiwi.bloonstd6epic", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.nuclearunicorn.kittensgame", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.PerennialHearts.BeggarsLife", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.playdigious.dungeonoftheendless", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.strayfawnstudio.dungeonclawlermobile", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.tinytitanstudios.TrainChu", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("com.unciv.app", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("games.sound.lente.spilled", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("io.anuke.mindustry", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("net.kairosoft.android.kingdom_en", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("net.kairosoft.android.piratedx", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("net.kairosoft.android.school2_en", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("net.kairosoft.android.starkairo_en", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("net.kairosoft.android.wakusei", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("nz.co.codepoint.minimetro", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("org.chucklefish.wargroove", AppCategory.GAME_STRATEGY_SIMULATION),
            packageRule("org.openttd.sdl", AppCategory.GAME_STRATEGY_SIMULATION),
            // Puzzle & Casual
            packageRule("com.denysdmytro.Oberty", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.erabit.methods.tdc.complete.gp", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.games.lumornis.luvinci", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.happybroccoligames.duckdetective2", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.headupgames.bridgeconstructorportal", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.headupgames.bridgeconstructortwd", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.kiarygames.tinydoors", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.MorionStudio.ConquistadorioFull", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.netflix.NGP.WorldOfPeppaPig", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.noodlecake.altosadventure", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.noodlecake.altosodyssey", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.playdead.limbo.full", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.polyhistor.numind", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.PotiPoti.IsThisSeatTaken", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.robtopx.geometryjump", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.snapbreak.boxes", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.snapbreak.theabandonedplanet", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.snapbreak.tinyrobots2", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.squareenixmontreal.lcgo", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.StudioGoya.CrackingTheCryptic", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.svencodes.sudokupad", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("com.webelinx.Rooms.Exits.EscapeRoom.FreeEscapeGames", AppCategory.GAME_PUZZLE_CASUAL),
            packageRule("de.application_systems.Growbot", AppCategory.GAME_PUZZLE_CASUAL),
            // Board & Card
            packageRule("com.aurumdust.ashofgods.theway", AppCategory.GAME_BOARD_CARD),
            packageRule("com.humble.SlayTheSpire", AppCategory.GAME_BOARD_CARD),
            packageRule("com.playstack.balatro.android", AppCategory.GAME_BOARD_CARD),
            packageRule("games.WanderlostInteractive.Dawncaster", AppCategory.GAME_BOARD_CARD)
        )

    private fun packageRule(packageName: String, category: AppCategory): KnownAppRule = KnownAppRule(
        selector = KnownAppSelector.ExactPackage(AppId(packageName)),
        category = category
    )
}
